### PR TITLE
Update ChestShop-towny to 1.18

### PR DESCRIPTION
**Pull request by BoyStijn**
updated api to latest version

### CODE REVIEW

**Comment by Phoenix616** [comment]
Ant chance you could fix up the diff in the pom?

Also does this not work on versions before 1.18 or why was that chosen as the api-vension in the plugin.yml?

Another thing: You removed the exception catch, is that no longer being possible?

**Comment by BoyStijn** [comment]
pom differences have been fixed
i haven't tested if it still functions on versions below 1.18 tho it will most likely depend on the versions of the dependencies
the exception catch was removed because that function no longer throws an error instead it returns null if user is not found (might have to catch that instead)

**Comment by Phoenix616** [comment]
Please rebase this on top of the latest changes. Also I see no reason to remove pre 1.18 support by changing the `api-version`, it looks like Towny is still compatible with most older versions so I set it to build against the 1.13 server now with the 1.13 api version (as ChestShop also still supports that) so just leave it at that.

Also generally speaking I'm not sure if this change is really necessary. I looked into Towny and it seems the API at those places still behaves the same way as before. (And even if it doesn't throw that exception anymore it seems to still include it so keeping it there should keep it compatible with older versions) So unless you have a proper reason for changing this (like the plugin throwing an error when used with newer Towny versions) I would prefer to just keep it as is.

Also for any further contributions: Please ensure that you keep the formatting consistent (you have random tabs in the pom as well as line ending changes) and in general the amount of changed lines as small as possible. (This applies to all open source contributions really, not just this project)

**Comment by BoyStijn** [comment]
i have figured out the issue of why my server would throw an error. The stable release is very outdated and does in fact crash, tho the lastest development version does work. I would recommend publishing a new stable version

**Pull request closed without merging**
